[package]
name = "apache_age"
description = "Rust driver for the Apache AGE. Based on postgres package"
license = "Apache-2.0"
version = "0.5.2"
edition = "2021"
repository = "https://github.com/dzordzu/rust-apache-age.git"
authors = [ "Tomasz Durda" ]
categories = ["database"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.1.0"
postgres = { version = "0.19.2" }
postgres-types = { version = "0.2.2", features = ["derive", "with-serde_json-1"] }
serde = { version = "1.0.136", features = ["derive"]}
serde_json = "1.0.79"
tokio-postgres = "0.7.5"
async-trait = { version = "0.1.53", optional = true }
rand = "0.8.5"
tokio = { version = "1.21.0", optional = true, features = ["macros", "rt-multi-thread"] }

[features]
default = ["sync", "tokio"]
tokio = ["dep:async-trait", "dep:tokio"]
sync = []
serializers = []
