[package]
name = "apache_age"
description = "Rust driver for the Apache AGE. Based on postgres package"
license = "Apache-2.0"
version = "0.2.1"
edition = "2021"
repository = "https://github.com/dzordzu/rust-apache-age.git"
authors = [ "Tomasz Durda" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.1.0"
postgres = { version = "0.19.2" }
postgres-types = { version = "0.2.2", features = ["derive", "with-serde_json-1"] }
serde = { version = "1.0.136", features = ["derive"]}
serde_json = "1.0.79"
tokio-postgres = "0.7.5"

[dev_dependencies]
rand = "0.8.5"
